//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EficazFramework.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controls() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EficazFramework.Resources.Strings.Controls", typeof(Controls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pesquisar....
        /// </summary>
        public static string AutoComplete_Tooltip {
            get {
                return ResourceManager.GetString("AutoComplete_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione o campo para pesquisa na coluna 1....
        /// </summary>
        public static string DataGridExpressionColumn_SelectedProperty_Null {
            get {
                return ResourceManager.GetString("DataGridExpressionColumn_SelectedProperty_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clique para selecionar uma data....
        /// </summary>
        public static string DateInputBox_Tooltip {
            get {
                return ResourceManager.GetString("DateInputBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar condição.
        /// </summary>
        public static string ExpressionBuilder_AddCommand {
            get {
                return ResourceManager.GetString("ExpressionBuilder_AddCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a e.
        /// </summary>
        public static string ExpressionBuilder_Between_Separator {
            get {
                return ResourceManager.GetString("ExpressionBuilder_Between_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo.
        /// </summary>
        public static string ExpressionBuilder_CL_Field {
            get {
                return ResourceManager.GetString("ExpressionBuilder_CL_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operador.
        /// </summary>
        public static string ExpressionBuilder_CL_Operator {
            get {
                return ResourceManager.GetString("ExpressionBuilder_CL_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        public static string ExpressionBuilder_CL_Value {
            get {
                return ResourceManager.GetString("ExpressionBuilder_CL_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remover condição.
        /// </summary>
        public static string ExpressionBuilder_DeleteCommand {
            get {
                return ResourceManager.GetString("ExpressionBuilder_DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisar.
        /// </summary>
        public static string ExpressionBuilder_FindCommand {
            get {
                return ResourceManager.GetString("ExpressionBuilder_FindCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisar.
        /// </summary>
        public static string ExpressionBuilder_Header {
            get {
                return ResourceManager.GetString("ExpressionBuilder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova seção.
        /// </summary>
        public static string SessionView_AddSessionLabel {
            get {
                return ResourceManager.GetString("SessionView_AddSessionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exibir todos os aplicativos.
        /// </summary>
        public static string StartMenu_AllApps {
            get {
                return ResourceManager.GetString("StartMenu_AllApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Olá.
        /// </summary>
        public static string StartMenu_DefaultWelcomeText {
            get {
                return ResourceManager.GetString("StartMenu_DefaultWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exibir aplicativos favoritos.
        /// </summary>
        public static string StartMenu_GridApps {
            get {
                return ResourceManager.GetString("StartMenu_GridApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aplicativos.
        /// </summary>
        public static string StartMenu_MainTab {
            get {
                return ResourceManager.GetString("StartMenu_MainTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iniciar.
        /// </summary>
        public static string StartMenu_MainTooltip {
            get {
                return ResourceManager.GetString("StartMenu_MainTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remover dos Favoritos.
        /// </summary>
        public static string StartMenu_PinOffApp {
            get {
                return ResourceManager.GetString("StartMenu_PinOffApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisar.
        /// </summary>
        public static string StartMenu_SearchTB {
            get {
                return ResourceManager.GetString("StartMenu_SearchTB", resourceCulture);
            }
        }
    }
}
