//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EficazFramework.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDescriptions() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EficazFramework.Resources.Strings.DataDescriptions", typeof(DataDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        public static string BoolToYesNo_False {
            get {
                return ResourceManager.GetString("BoolToYesNo_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sim.
        /// </summary>
        public static string BoolToYesNo_True {
            get {
                return ResourceManager.GetString("BoolToYesNo_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entre.
        /// </summary>
        public static string eComparer_Between {
            get {
                return ResourceManager.GetString("eComparer_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maior que.
        /// </summary>
        public static string eComparer_Bigger {
            get {
                return ResourceManager.GetString("eComparer_Bigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maior ou igual a.
        /// </summary>
        public static string eComparer_BiggerOrEqualThan {
            get {
                return ResourceManager.GetString("eComparer_BiggerOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contém.
        /// </summary>
        public static string eComparer_Contains {
            get {
                return ResourceManager.GetString("eComparer_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diferente de.
        /// </summary>
        public static string eComparer_Different {
            get {
                return ResourceManager.GetString("eComparer_Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Igual a.
        /// </summary>
        public static string eComparer_Equals {
            get {
                return ResourceManager.GetString("eComparer_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Igual a.
        /// </summary>
        public static string eComparer_Is {
            get {
                return ResourceManager.GetString("eComparer_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diferente de.
        /// </summary>
        public static string eComparer_IsNot {
            get {
                return ResourceManager.GetString("eComparer_IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Compr. do Texto.
        /// </summary>
        public static string eComparer_Length {
            get {
                return ResourceManager.GetString("eComparer_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Menor ou igual a.
        /// </summary>
        public static string eComparer_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("eComparer_LowerOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Menor que.
        /// </summary>
        public static string eComparer_LowerThan {
            get {
                return ResourceManager.GetString("eComparer_LowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inicia com.
        /// </summary>
        public static string eComparer_StartsWith {
            get {
                return ResourceManager.GetString("eComparer_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PIS ou NIT.
        /// </summary>
        public static string eDocumento_PIS_NIT {
            get {
                return ResourceManager.GetString("eDocumento_PIS_NIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Expressão.
        /// </summary>
        public static string eUpdateValueMode_Expression {
            get {
                return ResourceManager.GetString("eUpdateValueMode_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fixo.
        /// </summary>
        public static string eUpdateValueMode_Fixed {
            get {
                return ResourceManager.GetString("eUpdateValueMode_Fixed", resourceCulture);
            }
        }
    }
}
