//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EficazFramework.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Security {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Security() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EficazFramework.Resources.Strings.Security", typeof(Security).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acesso Negado.
        /// </summary>
        public static string GPO_AccessViolationHeader {
            get {
                return ResourceManager.GetString("GPO_AccessViolationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não possui credenciais necessárias para executar esta ação.
        /// </summary>
        public static string GPO_AccessViolationMessage {
            get {
                return ResourceManager.GetString("GPO_AccessViolationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acesso ao aplicativo.
        /// </summary>
        public static string GPO_AppAccess {
            get {
                return ResourceManager.GetString("GPO_AppAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inclusão.
        /// </summary>
        public static string GPO_AppAdd {
            get {
                return ResourceManager.GetString("GPO_AppAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclusão.
        /// </summary>
        public static string GPO_AppDelete {
            get {
                return ResourceManager.GetString("GPO_AppDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edição.
        /// </summary>
        public static string GPO_AppEdit {
            get {
                return ResourceManager.GetString("GPO_AppEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bloqueio de acesso a uma ou mais Entidades.
        /// </summary>
        public static string GPO_AppHiddenEntry {
            get {
                return ResourceManager.GetString("GPO_AppHiddenEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consulta e Exibição de Dados.
        /// </summary>
        public static string GPO_AppRead {
            get {
                return ResourceManager.GetString("GPO_AppRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve uma tentativa de violação às políticas de segurança..
        /// </summary>
        public static string GPO_DisableViolation {
            get {
                return ResourceManager.GetString("GPO_DisableViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número máximo de usuários conectados foi atingido..
        /// </summary>
        public static string GPO_MaximumNumberOfConnectionsReached {
            get {
                return ResourceManager.GetString("GPO_MaximumNumberOfConnectionsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma tentativa de acesso não autorizado..
        /// </summary>
        public static string GPO_NoIdentityLogon {
            get {
                return ResourceManager.GetString("GPO_NoIdentityLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua seção foi encerrada em função de um novo logon em outro dispositivo ou por um administrador de TI. Para mais informações solicite a um administrador um relatório das conexões ativas..
        /// </summary>
        public static string GPO_SessionEnd {
            get {
                return ResourceManager.GetString("GPO_SessionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve uma tentativa de acesso não autorizado às políticas de segurança..
        /// </summary>
        public static string GPO_Violation {
            get {
                return ResourceManager.GetString("GPO_Violation", resourceCulture);
            }
        }
    }
}
