//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EficazFramework.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EficazFramework.Resources.Strings.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verifique os erros apontados na validação, a seguir: {0}{1}.
        /// </summary>
        public static string Dialog_Message {
            get {
                return ResourceManager.GetString("Dialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informações inválidas.
        /// </summary>
        public static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os valores informados nos campos {0} e {1} devem ser idênticos..
        /// </summary>
        public static string EqualsTo {
            get {
                return ResourceManager.GetString("EqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma exceção ao realizar esta ação. Por favor tente novamente. Caso o erro persista entre em contato com o suporte..
        /// </summary>
        public static string Exception_DefaultContent {
            get {
                return ResourceManager.GetString("Exception_DefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oppss....
        /// </summary>
        public static string Exception_DefaultHeader {
            get {
                return ResourceManager.GetString("Exception_DefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CNPJ informado não é válido..
        /// </summary>
        public static string InvalidCNPJ {
            get {
                return ResourceManager.GetString("InvalidCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CNPJ ou CPF informado não é válido..
        /// </summary>
        public static string InvalidCNPJorCPF {
            get {
                return ResourceManager.GetString("InvalidCNPJorCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF informado não é válido..
        /// </summary>
        public static string InvalidCPF {
            get {
                return ResourceManager.GetString("InvalidCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail informado para o campo {0} não é válido..
        /// </summary>
        public static string InvalideMail {
            get {
                return ResourceManager.GetString("InvalideMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Inscrição Estadual informada não é válida para o Estado de {0}..
        /// </summary>
        public static string InvalidIE {
            get {
                return ResourceManager.GetString("InvalidIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Incrição Estadual não pode ser validada pois não há informações sobre UF..
        /// </summary>
        public static string InvalidIE_NoUF {
            get {
                return ResourceManager.GetString("InvalidIE_NoUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O PIS/PASEP informado não é válido..
        /// </summary>
        public static string InvalidPIS {
            get {
                return ResourceManager.GetString("InvalidPIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} só permite valores entre {1} e {2}..
        /// </summary>
        public static string InvalidRange {
            get {
                return ResourceManager.GetString("InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser menor que {1}..
        /// </summary>
        public static string InvalidRange_Maximum {
            get {
                return ResourceManager.GetString("InvalidRange_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser maior que {1}..
        /// </summary>
        public static string InvalidRange_Minimum {
            get {
                return ResourceManager.GetString("InvalidRange_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não pode ser menor que o campo {1}..
        /// </summary>
        public static string InvalidRangePeriod_Lower {
            get {
                return ResourceManager.GetString("InvalidRangePeriod_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não pode ser menor ou igual ao campo {1}..
        /// </summary>
        public static string InvalidRangePeriod_LowerOrEquals {
            get {
                return ResourceManager.GetString("InvalidRangePeriod_LowerOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser preenchido com no máximo {1} dígitos..
        /// </summary>
        public static string MaxLenght {
            get {
                return ResourceManager.GetString("MaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser preenchido com no mínimo {1} dígitos..
        /// </summary>
        public static string MinLenght {
            get {
                return ResourceManager.GetString("MinLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Repositório especificado não é auditável..
        /// </summary>
        public static string NotAuditableRepository {
            get {
                return ResourceManager.GetString("NotAuditableRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma entidade foi submetida para execução da validação..
        /// </summary>
        public static string NullInstance {
            get {
                return ResourceManager.GetString("NullInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não pode ficar em branco..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A validação do campo {0} gerou uma falha geral. Detalhes técnicos: {1}..
        /// </summary>
        public static string ValidationException {
            get {
                return ResourceManager.GetString("ValidationException", resourceCulture);
            }
        }
    }
}
