//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EficazFramework.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModel() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EficazFramework.Resources.Strings.ViewModel", typeof(ViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelando processamento em curso.
        /// </summary>
        public static string CancelingCurrentAsyncMethod {
            get {
                return ResourceManager.GetString("CancelingCurrentAsyncMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a revertendo operações, por favor aguarde....
        /// </summary>
        public static string DefaultCancelingMessage {
            get {
                return ResourceManager.GetString("DefaultCancelingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmar Operação.
        /// </summary>
        public static string DefaultConfirmMessage {
            get {
                return ResourceManager.GetString("DefaultConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a excluindo item(ns), por favor aguarde....
        /// </summary>
        public static string DefaultDeletingMessage {
            get {
                return ResourceManager.GetString("DefaultDeletingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a obtendo dados, por favor aguarde....
        /// </summary>
        public static string DefaultLoadingMessage {
            get {
                return ResourceManager.GetString("DefaultLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a gravando informações, por favor aguarde....
        /// </summary>
        public static string DefaultSavingMessage {
            get {
                return ResourceManager.GetString("DefaultSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação cancelada.
        /// </summary>
        public static string OperationCanceled_Title {
            get {
                return ResourceManager.GetString("OperationCanceled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um serviço do tipo {0} adicionado à instância de ViewModel..
        /// </summary>
        public static string ServiceAlreadyAdded {
            get {
                return ResourceManager.GetString("ServiceAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum Serviço do Tipo SingleEdit&lt;T&gt; foi anexado ao ViewModel..
        /// </summary>
        public static string SingleEditDetailWithoutMaster {
            get {
                return ResourceManager.GetString("SingleEditDetailWithoutMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente excluir o(s) item(ns) selecionado(s)?.
        /// </summary>
        public static string StoreService_BatchDeleteConfirmation_Message {
            get {
                return ResourceManager.GetString("StoreService_BatchDeleteConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente excluir o item selecionado?.
        /// </summary>
        public static string StoreService_DeleteConfirmation_Message {
            get {
                return ResourceManager.GetString("StoreService_DeleteConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmar exclusão.
        /// </summary>
        public static string StoreService_DeleteConfirmation_Title {
            get {
                return ResourceManager.GetString("StoreService_DeleteConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item excluído com sucesso.
        /// </summary>
        public static string StoreService_DeletedSucessfull_Message {
            get {
                return ResourceManager.GetString("StoreService_DeletedSucessfull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Itens excluídos com sucesso.
        /// </summary>
        public static string StoreService_DeletedSucessfull_MessageForBatch {
            get {
                return ResourceManager.GetString("StoreService_DeletedSucessfull_MessageForBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Concluído.
        /// </summary>
        public static string StoreService_DeletedSucessfull_Title {
            get {
                return ResourceManager.GetString("StoreService_DeletedSucessfull_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não encontramos nenhum resultado com os critérios de pesquisa informados..
        /// </summary>
        public static string StoreService_Get_NoRecords {
            get {
                return ResourceManager.GetString("StoreService_Get_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há nenhuma informação para ser exibida no momento..
        /// </summary>
        public static string StoreService_Get_NoRecords2 {
            get {
                return ResourceManager.GetString("StoreService_Get_NoRecords2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação de gravação cancelada pelo usuário.
        /// </summary>
        public static string StoreService_SaveCanceled_Message {
            get {
                return ResourceManager.GetString("StoreService_SaveCanceled_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados gravados com sucesso.
        /// </summary>
        public static string StoreService_SavedSucessfull_Message {
            get {
                return ResourceManager.GetString("StoreService_SavedSucessfull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Concluído.
        /// </summary>
        public static string StoreService_SavedSucessfull_Title {
            get {
                return ResourceManager.GetString("StoreService_SavedSucessfull_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma falha não esperada pelo aplicativo. Detalhes técnicos: {0}. Por gentileza entre em contato com o suporte..
        /// </summary>
        public static string UnhandledError_Message {
            get {
                return ResourceManager.GetString("UnhandledError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oopss....
        /// </summary>
        public static string UnhandledError_Title {
            get {
                return ResourceManager.GetString("UnhandledError_Title", resourceCulture);
            }
        }
    }
}
